kitapcanavari/kitapcanavari/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kitapcanavari.Models;
using kitapcanavari.DAL;
using PagedList;
using System.Globalization;
using kitapcanavari.Models;

namespace kitapcanavari.Controllers
{
    public class HomeController : Controller
    {
        private kitapcanavariContext db = new kitapcanavariContext();
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Arama(string arama)
        {
            var items = (from p in db.Uruns where (p.Ad.Contains(arama) || p.Detay.Contains(arama) || p.Kategori.Contains(arama)) orderby p.ID descending select p).ToPagedList(1, 4);
            ViewBag.aranan = arama;
            return View(items);
        }

        [Route("Home/Arama/{arama}/{sayfa}")]
        public ActionResult Arama(string arama, int sayfa)
        {
            var items = (from p in db.Uruns where (p.Ad.Contains(arama) || p.Detay.Contains(arama) || p.Kategori.Contains(arama)) orderby p.ID descending select p).ToPagedList(sayfa, 4);
            ViewBag.aranan = arama;
            return View(items);
        }

        [Route("Urunler/{Kategori}/{sayfa}")]
        public ActionResult Listele(string Kategori, int sayfa = 1)
        {
            
            ViewBag.Title = Kategori;
            ViewBag.Kategori = Kategori;
            var query = (from p in db.Uruns where (p.Kategori == Kategori) orderby p.ID descending select p).ToPagedList(sayfa, 4);
            return View(query);
        }

        public ActionResult UrunDetay(int id = 0)
        {
            if (id == 0)
            {
                return RedirectToAction("Index");
            }
            Urun urun;
            urun = db.Uruns.Find(id);
            db.SaveChanges();
            return View(urun);
        }
        public ActionResult ChangeCulture(string lang, string returnUrl)
        {
            Session["Culture"] = new CultureInfo(lang);
            return Redirect(returnUrl);
        }
    }

}

kitapcanavari/kitapcanavari/Controllers/SepetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using kitapcanavari.Models;
using kitapcanavari.DAL;

namespace kitapcanavari.com.Controllers
{
    public class SepetController : Controller
    {
        private kitapcanavariContext db = new kitapcanavariContext();
        // GET: Sepet
        public ActionResult Index()
        {
            if (Session["uye_id"] == null)
                return RedirectToAction("GirisYap", "Uyes");
            List<Urun> listeDondur = new List<Urun>();
            if (Session["sepet"] == null)
            {
                return View(listeDondur);
            }
            listeDondur = (List<Urun>)Session["sepet"];
            return View(listeDondur);
        }

        public ActionResult SepetEkle(int id)
        {
            List<Urun> liste = new List<Urun>();
            Urun tmp = db.Uruns.Find(id);
            if (tmp == null)
            {
                return RedirectToAction("Index");
            }
            if (tmp.Adet == 0)
            {
                return Content("<script>alert('Bu üründen stokda kalmamıştır.');window.history.back(-1);</script>", "text/html");
            }
            if (Session["uye_id"] == null)
            {
                RedirectToAction("GirisYap", "Uyes");
            }
            if (Session["sepet"] != null)
                liste.AddRange((List<Urun>)Session["sepet"]);
            liste.Add(tmp);
            Session["sepet"] = liste;
            return RedirectToAction("Index");
        }
        public ActionResult Cikar(int id)
        {
            List<Urun> listeCikar = new List<Urun>();
            listeCikar = (List<Urun>)Session["sepet"];
            Urun tmp = listeCikar.Find(x => x.ID == id);
            if (tmp == null)
            {
                return RedirectToAction("Index");
            }
            listeCikar.Remove(tmp);
            Session["sepet"] = listeCikar;
            return RedirectToAction("Index");
        }
        public ActionResult SatinAl()
        {
            if (Session["uye_id"] == null)
            {
                return RedirectToAction("GirisYap", "Uyes");
            }
            if (Session["sepet"] == null)
            {
                return Content("<script>alert('Sepette satın alınacak ürün bulunmamaktadır.');window.location='/Uyes/Profil';</script>", "text/html");
            }
            List<Urun> listeSil = new List<Urun>();
            listeSil = (List<Urun>)Session["sepet"];
            Urun tmp;
            foreach (var i in listeSil)
            {
                tmp = db.Uruns.Find(i.ID);
                if (tmp.Adet >= 1)
                {
                    tmp.Adet--;
                    db.SaveChanges();
                }
                else
                    continue;
            }
            Session["sepet"] = null;
            return Content("<script>alert('Ürünler satın alındı.');window.location='/Sepet/Index';</script>", "text/html");
        }
    }
}

kitapcanavari/kitapcanavari/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

kitapcanavari/kitapcanavari/Views/Home/Arama.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<kitapcanavari.Models.Urun>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <hr />
    <div class="row">
        @if (Model.Count() == 0)
        {
            <div class="row text-center"><h1>Aranan sonuç bulunamadı.</h1></div>
        }
        @foreach (var i in Model)
        {
            <div class="col-sm-4 col-xs-6 col-md-3 text-center">
                <div class="thumbnail">
                    <a href="@Url.Action("UrunDetay/"+@Html.DisplayFor(item => i.ID))"><img src=@Html.DisplayFor(item => i.ResimYol) class="img-responsive" alt="..."></a>
                    <div class="caption">
                        <h3>@Html.DisplayFor(item => i.Ad)</h3>
                        <b>@Html.DisplayFor(item => i.Detay)</b>
                        <p><span class="label label-success">@Html.DisplayFor(item => i.Fiyat) TL</span></p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="pagedList row text-center">
        @Html.PagedListPager(Model, sayfa => Url.Action("Arama/" + ViewBag.aranan + "/" + sayfa), PagedListRenderOptions.PageNumbersOnly)
    </div>

</body>
</html>

kitapcanavari/kitapcanavari/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

kitapcanavari/kitapcanavari/Views/Home/Index.cshtml
@{
    ViewBag.Title = "kitapcanavari";
}

<hr />
<div class="row">
    <div class="col-md-3 col-xs-12">
        @RenderPage("~/Views/Home/Kategori.cshtml")
        <hr />
    </div>

    <div class="col-md-9 col-xs-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>

            <!-- slides -->
            <div class="carousel-inner">
                <div class="item active">
                    <img src="http://st3.myideasoft.com/shop/cr/19/myassets/products/078/pr_01_2078.jpg?revision=1453798359 " width="400" height="400" alt="...">
                    <div class="carousel-caption">
                        <h3>HOBBİT</h3>
                    </div>
                </div>
                <div class="item">
                    <img src="http://mcdn01.gittigidiyor.net/24727/tn120/247278438_tn120_0.jpg?1481826990" width="600" height="600" alt="...">
                    <div class="carousel-caption">
                        <h3>STEPHEN KING</h3>
                    </div>
                </div>
                <div class="item">
                    <img src="https://www.harmankitap.com/u/orhunkitap/img/b/t/a/tarihset-1428708158.png" width="600" height="600" alt="...">
                    <div class="carousel-caption">
                        <h3>TÜRKLERİN TARİHİ</h3>
                    </div>
                </div>
            </div>

            <!-- Controls -->
         
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

kitapcanavari/kitapcanavari/Views/Home/Kategori.cshtml
@{
    ViewBag.Title = "Kategori";
}

<div class="panel-group" id="accordion">
    <div class="panel panel-default" style="background-color:cornflowerblue">
        <div class="panel-heading" style="background-color:cornflowerblue">
            <h4 class="panel-title">
                <a href="Urunler/SiirKitaplari/1">@kitapcanavari.Resources.lang.SiirKitaplari</a>
            </h4>
        </div>
    </div>
</div>
<div class="panel-group" id="accordion">
    <div class="panel panel-default" style="background-color:cornflowerblue">
        <div class="panel-heading" style="background-color:cornflowerblue">
            <h4 class="panel-title">
                <a href="Urunler/Romanlar/1">@kitapcanavari.Resources.lang.Romanlar</a>
            </h4>
        </div>
    </div>
</div>
<div class="panel-group" id="accordion">
    <div class="panel panel-default" style="background-color:cornflowerblue">
        <div class="panel-heading" style="background-color:cornflowerblue">
            <h4 class="panel-title">
                <a href="Urunler/Tarih/1">@kitapcanavari.Resources.lang.Tarih</a>
            </h4>
        </div>
    </div>
</div>
<div class="panel-group" id="accordion">
    <div class="panel panel-default" style="background-color:cornflowerblue">
        <div class="panel-heading" style="background-color:cornflowerblue">
            <h4 class="panel-title">
                <a href="Urunler/KisiselGelisim/1">@kitapcanavari.Resources.lang.KisiselGelisim</a>
            </h4>
        </div>
    </div>
</div>

kitapcanavari/kitapcanavari/Views/Home/Listele.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<kitapcanavari.Models.Urun>
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <hr />
    <div class="row">
        @if (Model.Count() == 0)
        {
            <div class="row text-center"><h1>@kitapcanavari.Resources.lang.BuKategorideUrunYok</h1></div>
        }


        @foreach (var i in Model)
        {
            <div class="col-sm-4 col-xs-6 col-md-3 text-center">
                <div class="thumbnail">
                    <a href="@Url.Action("UrunDetay/"+@Html.DisplayFor(item => i.ID))"><img src=@Html.DisplayFor(item => i.ResimYol) class="img-responsive" alt="..."></a>
                    <div class="caption">
                        <h4>@Html.DisplayFor(item => i.Ad)</h4>
                        <p>@Html.DisplayFor(item => i.Detay)</p>
                        <p><span class="label label-success">@Html.DisplayFor(item => i.Fiyat) TL</span></p>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="pagedList row text-center">
        @Html.PagedListPager(Model, sayfa => Url.Action(ViewBag.Cinsiyet + "/" + ViewBag.Kategori + "/" + sayfa, "Urunler"), PagedListRenderOptions.PageNumbersOnly)
    </div>
</body>
</html>

kitapcanavari/kitapcanavari/Views/Home/UrunDetay.cshtml
@model kitapcanavari.Models.Urun

@{
    ViewBag.Title = @Html.DisplayFor(model => model.Ad) + " - " + @Html.DisplayFor(model => model.Detay);
}

<div class="row text-center">
    <div class="col-md-5">
        <img src="@Html.DisplayFor(model => model.ResimYol)" class="img-responsive" />
    </div>
    <div class="col-md-7">
        <p><h1 class="text-primary"><b>@Html.DisplayFor(model => Model.Ad)</b></h1></p>
        <p><h4>@Html.DisplayFor(model => Model.Detay)</h4></p>
        <p><h4 class="text-success">@Html.DisplayFor(model => Model.Fiyat) TL</h4></p>
        <p><a href="@Url.Action("SepetEkle/" + @Html.DisplayFor(model => model.ID),"Sepet")" class="btn btn-success">Sepete Ekle</a></p>
    </div>
</div>