kitapcanavari/kitapcanavari/Models/Uye.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace kitapcanavari.Models
{
    public class Uye
    {
        public int ID { get; set; }

        [Required(ErrorMessageResourceType = typeof (kitapcanavari.Resources.lang), ErrorMessageResourceName = "LutfenAdGir")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Lütfen adınızı 3-20 karakter uzunluğunda giriniz.")]
        public string Ad { get; set; }


        [Required(ErrorMessageResourceType = typeof(kitapcanavari.Resources.lang), ErrorMessageResourceName = "LutfenSoyadGir")]
        [StringLength(20, MinimumLength = 3, ErrorMessage = "Lütfen soyadınızı 3-20 karakter uzunluğunda giriniz.")]
        public string Soyad { get; set; }

        [Display(Name = "E-posta")]

        [Required(ErrorMessageResourceType = typeof(kitapcanavari.Resources.lang), ErrorMessageResourceName = "LutfenEpostaGir")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Lütfen e-posta adresinizi geçerli bir formatta giriniz.")]
        public string Eposta { get; set; }

        [Display(Name = "Şifre")]

        [Required(ErrorMessageResourceType = typeof(kitapcanavari.Resources.lang), ErrorMessageResourceName = "LutfenSifreGir")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }

        [Display(Name = "Rütbe")]
        public string Rutbe { get; set; }

        public virtual List<Iletisim> Iletisim { get; set; }
    }
    public class GirisModel
    {

        [Required(ErrorMessageResourceType = typeof(kitapcanavari.Resources.lang), ErrorMessageResourceName = "LutfenEpostaGir")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Lütfen e-posta adresinizi geçerli bir formatta giriniz.")]
        public string Eposta { get; set; }


        [Required(ErrorMessageResourceType = typeof(kitapcanavari.Resources.lang), ErrorMessageResourceName = "LutfenSifreGir")]
        [DataType(DataType.Password)]
        public string Sifre { get; set; }
    }
}

kitapcanavari/kitapcanavari/Controllers/UrunsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using kitapcanavari.DAL;
using kitapcanavari.Models;

namespace kitapcanavari.Controllers
{
    public class UrunsController : Controller
    {
        private kitapcanavariContext db = new kitapcanavariContext();

        // GET: Uruns
        [Filter.Admin]
        public ActionResult Index()
        {
            return View(db.Uruns.ToList());
        }

        // GET: Uruns/Details/5
        [Filter.Admin]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // GET: Uruns/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Urun urun, HttpPostedFileBase resim)
        {
            if (ModelState.IsValid)
            {
                db.Uruns.Add(urun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(urun);
        }

        // GET: Uruns/Edit/5
        [Filter.Admin]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: Uruns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Filter.Admin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Ad,Detay,Kategori,Fiyat,ResimYol,Adet")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(urun);
        }

        // GET: Uruns/Delete/5
        [Filter.Admin]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: Uruns/Delete/5
        [Filter.Admin]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urun urun = db.Uruns.Find(id);
            db.Uruns.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

kitapcanavari/kitapcanavari/Controllers/UyesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using kitapcanavari.Models;
using System.Security.Cryptography;
using System.Text;
using kitapcanavari.DAL;

namespace kitapcanavari.com.Controllers
{
    public class UyesController : Controller
    {
        private kitapcanavariContext db = new kitapcanavariContext();

        // GET: Uyes
        [Filter.Admin]
        public ActionResult Index()
        {
            return View(db.Uyes.ToList());
        }

        // GET: Uyes
        [Filter.Admin]
        public ActionResult AdminPanel()
        {
            ViewBag.Son20Urun = db.Uruns.OrderByDescending(i => i.ID).Take(20).ToList();
            ViewBag.Son20Uye = db.Uyes.OrderByDescending(i => i.ID).Take(20).ToList();
            ViewBag.UrunSayisi = db.Uruns.Count();
            ViewBag.UyeSayisi = db.Uyes.Count();

            return View();
        }

        // GET: Uyes/Details/5
        [Filter.Admin]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyes.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }


        // GET: Uyes/Create
        public ActionResult UyeOl()
        {
            return View();
        }

        // POST: Uyes/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UyeOl(Uye uye)
        {
            uye.Sifre = kitapcanavari.Controllers.Fonksiyonlar.MD5Sifrele(uye.Sifre);
            uye.Rutbe = "Yönetici";
            if (ModelState.IsValid)
            {
                db.Uyes.Add(uye);
                db.SaveChanges();
                Session["Yetki"] = uye.Rutbe;
                Session["Username"] = uye.Ad;
                Session["uye_id"] = uye.ID;
                return RedirectToAction("Index");
            }

            return View(uye);
        }

        // GET: Uyes/Edit/5
        [Filter.Admin]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyes.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // POST: Uyes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Filter.Admin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uye).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(uye);
        }

        // GET: Uyes/Delete/5
        [Filter.Admin]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Uye uye = db.Uyes.Find(id);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        // POST: Uyes/Delete/5
        [Filter.Admin]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Uye uye = db.Uyes.Find(id);
            uye.Iletisim = db.Iletisims.Where(x => x.Uye.ID == uye.ID).ToList();
            db.Uyes.Remove(uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult CikisYap()
        {
            Session.Clear();
            return RedirectToAction("Index");
        }

        public ActionResult GirisYap()
        {
            if (Session["Yetki"] != null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public ActionResult GirisYap(GirisModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            string tempSifre = kitapcanavari.Controllers.Fonksiyonlar.MD5Sifrele(model.Sifre as string);
            Uye uye = (from i in db.Uyes where i.Sifre == tempSifre && i.Eposta == model.Eposta select i).SingleOrDefault();
            if (uye != null)
            {
                Session["Yetki"] = uye.Rutbe;
                Session["Username"] = uye.Ad;
                Session["uye_id"] = uye.ID;

                if (uye.Rutbe == "Yönetici")
                    return RedirectToAction("AdminPanel");

                else
                    return RedirectToAction("Index");
            }
            ViewBag.uyari = "Lütfen bilgilerinizi kontrol ediniz !";
            return View();
        }

        public ActionResult Profil()
        {
            if (Session["sepet"] != null)
                ViewBag.Sepet = Session["sepet"] as List<Urun>;
            else
                ViewBag.Sepet = null;

            var uyeBilgi = db.Uyes.Find(Session["uye_id"]);

            var Adresler = db.Iletisims.Where(x => x.Uye.ID == uyeBilgi.ID).ToList();

            if (Adresler != null)
                ViewBag.Adresler = Adresler;
            else
                ViewBag.Adresler = null;

            ViewBag.UyeBilgi = uyeBilgi;
            return View();
        }
        public ActionResult AdresEkle()
        {
            if (Session["Yetki"] == null)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public ActionResult AdresEkle(Iletisim iletisim)
        {

            if (ModelState.IsValid)
            {
                iletisim.Uye = db.Uyes.Find(Session["uye_id"]);
                db.Iletisims.Add(iletisim);
                db.SaveChanges();
                return RedirectToAction("Profil");
            }

            return View();
        }
        public ActionResult Guncelle()
        {
            if (Session["uye_id"] == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var uye = db.Uyes.Find(Session["uye_id"]);
            if (uye == null)
            {
                return HttpNotFound();
            }
            return View(uye);
        }

        [HttpPost]
        public ActionResult Guncelle(Uye uye)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uye).State = EntityState.Modified;
                uye.Sifre = kitapcanavari.Controllers.Fonksiyonlar.MD5Sifrele(uye.Sifre);
                uye.Rutbe = (string)Session["Yetki"];
                db.SaveChanges();
                return RedirectToAction("Profil", "Uyes");
            }
            return View(uye);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

kitapcanavari/kitapcanavari/Views/Uyes/AdminPanel.cshtml
@{
    ViewBag.Title = @kitapcanavari.Resources.lang.AdminPanel;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<hr />
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/Uyes/UyeOl">@kitapcanavari.Resources.lang.KayitEkle</a></li>
                <li><a href="/Uruns">@kitapcanavari.Resources.lang.Urunler</a></li>
            </ul>

        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="row">
    <div class="col-md-6">
        <table class="table table-bordered">
            <tr>
                <td colspan="6" class="text-center text-info"><b>@kitapcanavari.Resources.lang.Son20Urun</b></td>
            </tr>
            <tr>
                <th>@kitapcanavari.Resources.lang.Ad</th>
                <th>@kitapcanavari.Resources.lang.Detay</th>
                <th>@kitapcanavari.Resources.lang.Kategori</th>
                <th>@kitapcanavari.Resources.lang.Fiyat</th>
                <th>@kitapcanavari.Resources.lang.Adet</th>
            </tr>

            @foreach (var item in ViewBag.Son20Urun)
            {
                <tr>
                    <td>@item.Ad</td>
                    <td>@item.Detay</td>
                    <td> @item.Kategori</td>
                    <td>@item.Fiyat</td>
                    <td>@item.Adet</td>
                    <td>
                        <a href="@Url.Action("Edit", "Uruns", new { id = item.ID })"><span class="glyphicon glyphicon-edit"></span></a>
                        <a href="@Url.Action("Details", "Uruns", new { id = item.ID })"><span class="glyphicon glyphicon-zoom-in"></span></a>
                        <a href="@Url.Action("Delete", "Uruns", new { id = item.ID })"><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            }
        </table>

    </div>


    <div class="col-md-6">
        <table class="table table-bordered">
            <tr>
                <td colspan="6" class="text-center text-info"><b>@kitapcanavari.Resources.lang.Son20Uye</b></td>
            </tr>
            <tr>
                <th>@kitapcanavari.Resources.lang.Ad</th>
                <th>@kitapcanavari.Resources.lang.Soyad</th>
                <th>@kitapcanavari.Resources.lang.Eposta</th>

            </tr>

            @foreach (var item in ViewBag.Son20Uye)
            {
                <tr>
                    <td>@item.Ad</td>
                    <td>@item.Soyad</td>
                    <td> @item.Eposta</td>
                    <td>
                        <a href="@Url.Action("Edit", "Uyes", new { id = item.ID })"><span class="glyphicon glyphicon-edit"></span></a>
                        <a href="@Url.Action("Details", "Uyes", new { id = item.ID })"><span class="glyphicon glyphicon-zoom-in"></span></a>
                        <a href="@Url.Action("Delete", "Uyes", new { id = item.ID })"><span class="glyphicon glyphicon-remove"></span></a>
                    </td>
                </tr>
            }
        </table>

    </div>
</div>

kitapcanavari/kitapcanavari/Views/Uyes/AdresEkle.cshtml
@model kitapcanavari.Models.Iletisim

@{
    ViewBag.Title = @kitapcanavari.Resources.lang.YeniAdresEkle;
}

<h2>@kitapcanavari.Resources.lang.YeniYarat</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>@kitapcanavari.Resources.lang.YeniAdresEkle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sehir, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sehir, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sehir, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Semt, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Semt, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Semt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostaKodu, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostaKodu, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostaKodu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefon, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@kitapcanavari.Resources.lang.Ekle class="btn btn-default" />
            </div>
        </div>
    </div>
}

kitapcanavari/kitapcanavari/Views/Uyes/Create.cshtml
@model kitapcanavari.Models.Uye

@{
    ViewBag.Title = @kitapcanavari.Resources.lang.YeniUyeEkle;
}

<h2>@kitapcanavari.Resources.lang.YeniYarat</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@kitapcanavari.Resources.lang.Uye</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Eposta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eposta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rutbe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rutbe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rutbe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@kitapcanavari.Resources.lang.Ekle class="btn btn-default" />
            </div>
        </div>
    </div>
}

kitapcanavari/kitapcanavari/Views/Uyes/Delete.cshtml
@model kitapcanavari.Models.Uye

@{
    ViewBag.Title = @kitapcanavari.Resources.lang.Sil;
}

<h2>@kitapcanavari.Resources.lang.Sil</h2>

<div>
    <h4>@kitapcanavari.Resources.lang.Uye</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @kitapcanavari.Resources.lang.Ad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @kitapcanavari.Resources.lang.Soyad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyad)
        </dd>

        <dt>
            @kitapcanavari.Resources.lang.Eposta
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eposta)
        </dd>

        <dt>
            @kitapcanavari.Resources.lang.Sifre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifre)
        </dd>

        <dt>
            @kitapcanavari.Resources.lang.Rutbe
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutbe)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value=@kitapcanavari.Resources.lang.Sil class="btn btn-default" />
        </div>
    }
</div>

kitapcanavari/kitapcanavari/Views/Uyes/Details.cshtml
@model kitapcanavari.Models.Uye

@{
    ViewBag.Title = @kitapcanavari.Resources.lang.Detaylar;
}

<h2>@kitapcanavari.Resources.lang.Detaylar</h2>

<div>
    <h4>@kitapcanavari.Resources.lang.Uye</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @kitapcanavari.Resources.lang.Ad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @kitapcanavari.Resources.lang.Soyad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Soyad)
        </dd>

        <dt>
            @kitapcanavari.Resources.lang.Eposta
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Eposta)
        </dd>

        <dt>
            @kitapcanavari.Resources.lang.Sifre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sifre)
        </dd>

        <dt>
            @kitapcanavari.Resources.lang.Rutbe
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rutbe)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(@kitapcanavari.Resources.lang.Duzenle, "Edit", new { id = Model.ID })
</p>

kitapcanavari/kitapcanavari/Views/Uyes/Edit.cshtml
@model kitapcanavari.Models.Uye

@{
    ViewBag.Title = @kitapcanavari.Resources.lang.Duzenle;
}

<h2>Düzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@kitapcanavari.Resources.lang.Uye</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Soyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Soyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Eposta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Eposta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Eposta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rutbe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rutbe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rutbe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@kitapcanavari.Resources.lang.Kaydet class="btn btn-default" />
            </div>
        </div>
    </div>
}